spring:
  application:
    name:
  web:
    error:
      include-stacktrace: always
  # MySQL
  datasource:
    url:
    username:
    password:
    driver-class-name:
  # Mybatis
mybatis:
  mapper-locations:
  type-aliases-package:



logging:
  file:
    # 로그 파일 경로
    name: logs/error.log
  level:
    # 로그 출력 레벨 설정 (trace, debug, info, warn, error)
    root: error

    # 특정 패키지만 로그 출력 레밸 설정
    com.msa4meerkatgram.controllers: debug