spring:
  application:
    name: msa4-meerkatgram
    version: v1

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  # DB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:meerkatgram}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:msa505}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 커넥션 풀 설정
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  # JPA
  jpa:
    hibernate:
      # 서버를 재시작 할 때, DB 스키마를 어떻게 관리할지 설정
      # `none` 이외의 설정 값을 사용시, DB 스키마가 초기화 되거나 수정되므로 요주의
      # 설정 값
      #    - `none`: 스키마 자동 생성 비활성화 (Default)
      #    - `update`: 기존 테이블을 유지하며 변경 사항만 업데이트
      #    - `create`: 애플리케이션 실행 시 테이블 생성 (기존 데이터 삭제됨)
      #    - `create-drop`: 애플리케이션 종료 시 테이블 삭제
      #    - `validate`: 기존 테이블의 구조를 검증하고, 일치하지 않으면 예외 발생
      ddl-auto: create-drop
    # 실행되는 SQL을 콘솔에 출력 여부
    show-sql: true
    properties:
      hibernate:
        # SQL을 보기 좋게 포맷하여 출력
        format_sql: true
    # 데이터 소스 초기화 지연 설정
      # - true로 설정 시, Spring 컨텍스트가 완전히 로드된 후에 어플리케이션의 DataSource 초기화
    defer-datasource-initialization: true
  sql:
    init:
      # DB 초기화 파일의 위치 설정
      data-locations: classpath*:dummy/*.sql
      # DB 초기화 파일이 실행될 시점을 설정
      #      - `embedded`: 내장 데이터베이스일 경우에만 초기화 파일 실행
      #      - `always`: 모든 데이터 베이스에서 초기화 파일 항상 실행
      #      - `never`: 실행하지 않음
      mode: never
      # 사용할 DB 플랫폼 설정
      #   - all :  모든 플랫폼에서 설정을 적용
      #   - h2, mysql 등 : 특정 데이터베이스에만 초기화 파일을 실행
      platform: all

server:
  error:
    include-stacktrace: always
    include-message: always

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.msa4meerkatgram

# Log
logging:
  file:
    # 로그 파일 경로
    name: logs/error.log
  level:
    # 로그 출력 레벨 설정 (trace, debug, info, warn, error)
    root: info

    # 특정 패키지만 로그 출력 레벨 설정
    com.msa4spring.controllers: debug

# Security & JWT
security:
  jwt:
    secure: false
    issuer: meerkat@meerkat.kr
    type: JWT
    access-token-expiry: 100000000
    refresh-token-expiry: 1296000000
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1296000
    secret: ${JWT_SECRET:34589hf72349q8925h8q39f5h72934hf59q28h346f5983qo4gfo53q4g53q4g}
    header-key: Authorization
    scheme: Bearer
    reissue-uri: /api/reissue-token

# file
file:
  server-uri: ${SERVER_URI:http://localhost:8080}
  storage-path: /storage
  profile-path: /files/profiles
  post-path: /files/posts
  allow-extension-list: [
    "image/jpg",
    "image/jpeg",
    "image/png",
    "image/gif",
    "image/svg",
    "image/webp"
  ]

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
  max-age: 3600